# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Volunteer-System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Build Frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      # Build Backend
      - name: Build backend
        run: |
          cd backend
          npm install
          npm run build
          cd ..

      # Archive the build artifacts from both frontend and backend
      - name: Archive production artifacts
        run: |
          zip -r frontend.zip frontend/build/*
          zip -r backend.zip backend/build/*

      # Upload frontend artifact
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: frontend.zip

      # Upload backend artifact
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      # Download frontend artifact
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact

      # Download backend artifact
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      # Unzip frontend
      # - name: Unzip frontend artifact for deployment
      #   run: unzip frontend.zip

      # Unzip backend
      # - name: Unzip backend artifact for deployment
      #   run: unzip backend.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EC1DFC4515BF4C82BE2F4BBF8516F079 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_98C2493A8E5846BFA18B2EF5879423CE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6AD24C7F64FD4AEDA7B5FB25B0621F43 }}

      # - name: 'Deploy to Azure Web App'
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: 'Volunteer-System'
      #     slot-name: 'Production'
      #     package: .
      
      # Deploy Frontend to Azure Web App
      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend'
          slot-name: 'production' # Remove this line if not deploying to a slot
          package: './frontend.zip'

            # Deploy Backend to Azure Web App
      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend'
          slot-name: 'production' # Remove this line if not deploying to a slot
          package: './backend.zip'
          